In [40]:
import pandas as pd
import collections
patientdata = []
for filenum in range(1,71):
    patientnum = 'Patient Number ' + str(filenum)
    if(filenum<10):
        with open("C:\\Users\\Ayman\\Documents\\machinelearning\\hw1\\diabetes-data\\data-0"+str(filenum), "r") as file:
            for line in file:
                fourth = str(line)
                date = fourth[0:fourth.index('\t')]
                fourth = fourth.replace(date,'')
                fourth = fourth.replace('\t','',1)
                time = fourth[0:fourth.index('\t')]
                fourth = fourth.replace(time,'')
                fourth = fourth.replace('\t','',1)
                third = fourth[0:fourth.index('\t')]
                fourth = fourth.replace(third,'')
                fourth = fourth.replace('\t','',1)
                fourth = fourth.replace('\n','')
                #patientdata.append([patientnum,date,time,third,fourth])
                try:
                    patientdata.append([float(third),float(fourth)])
                except:
                    patientdata.append([float(third),0.0])
    else:
        with open("C:\\Users\\Ayman\\Documents\\machinelearning\\hw1\\diabetes-data\\data-"+str(filenum), "r") as file:
            for line in file:
                fourth = str(line)
                date = fourth[0:fourth.index('\t')]
                fourth = fourth.replace(date,'')
                fourth = fourth.replace('\t','',1)
                time = fourth[0:fourth.index('\t')]
                fourth = fourth.replace(time,'')
                fourth = fourth.replace('\t','',1)
                third = fourth[0:fourth.index('\t')]
                fourth = fourth.replace(third,'')
                fourth = fourth.replace('\t','',1)
                fourth = fourth.replace('\n','')
                #patientdata.append([patientnum,date,time,third,fourth])
                try:
                    patientdata.append([float(third),float(fourth)])
                except:
                    patientdata.append([float(third),0.0])
df = pd.DataFrame(patientdata, columns=['3rd','4th'])
df

        3rd    4th
0      58.0  100.0
1      33.0    9.0
2      34.0   13.0
3      62.0  119.0
4      33.0    7.0
...     ...    ...
29325  33.0    1.0
29326  34.0    7.0
29327  34.0    7.0
29328  34.0    7.0
29329  34.0    7.0

[29330 rows x 2 columns]

In [ ]:
import pandas as pd
import numpy as np


def distance(x1, x2):
    return np.sqrt(np.sum((x1 - x2)**2))


def center(data, k):
    index = np.random.choice(len(data), k, replace=False)
    centers = data[index]
    return centers


def cluster(data, centers):
    distances = np.array([[distance(point, center) for center in centers] for point in data])
    return np.argmin(distances, axis=1)
#attain distances and place points into clusters

def updatecenters(data, label, k):
    centers = np.zeros((k, data.shape[1]))
    for x in range(k):
        points = data[label == x]
        if len(points) > 0:
            centers[x] = np.mean(points, axis=0)
    return centers
#provide new centers to update the cluster 

def score(data, labels):
    distances = np.array([[distance(data[i], data[j]) for j in range(len(data))] for i in range(len(data))])
    a = np.array([np.mean(distances[i, labels == labels[i]]) for i in range(len(data))])
    b = np.array([np.min([np.mean(distances[i, labels == j]) for j in range(len(set(labels))) if j != labels[i]]) for i in range(len(data))])
    s = (b - a) / np.maximum(a, b)
    return np.mean(s)


dataarr = df[['3rd', '4th']].to_numpy()
kval = [5]#testing to see if it can work with one then upscale to more ks

for k in kval:
    centerr = center(dataarr, k)
    pastlabel = np.zeros(len(dataarr))
    while True:#loops continuously untill there is no more change
        labels = cluster(dataarr, centerr)
        if np.array_equal(labels, pastlabel):
            print(k)
            scores = score(dataarr, labels)  
            print("Silhouette Score:", scores)
            break
        else:
            centerr = updatecenters(dataarr, labels, k)
            pastlabel = labels
scores = score(dataarr,labels)

5